site_name: お江戸のチケット管理
site_url: http://oedodevelopersclub.github.io/TicketsManagerDocs/
repo_url: https://github.com/OedoDevelopersClub/TicketsManagerDocs
pages:
- HOME: index.md
- 概要: overview.md
- 開発者向け:
    - 目次: forDevelopers/index.md
    - 開発環境の概要: forDevelopers/overview.md
    - 開発環境構築手順 for Eclipse: forDevelopers/How_to_Setup_Development_Environment_Eclipse.md
    - 開発環境構築手順 for NetBeans: forDevelopers/How_to_Setup_Development_Environment_NetBeans.md
    - Appendix: forDevelopers/tips/Using_Better_Font_for_Programming.md
theme: mkdocs
